name: dev build
on:
  pull_request: {}
jobs:
  dev-build:
    if: github.actor!= 'dependabot-preview[bot]'
    name: build
    runs-on:
      group: CI
      labels: ci
    timeout-minutes: 5
    env:
      AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
      AWS_REGION: ${{ vars.AWS_REGION }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: pwd
      - run: ls -la
      - name: build docker
        id: build
        run: |
          printenv
          apollo-ng
